spring:
  datasource:
    url: jdbc:postgresql://db.rawctbvnbsmbnfmdxipu.supabase.co:5432/postgres
    username: postgres
    password: xuP0j5y2BlKwhzn3
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
